 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/decare:$COMMIT_SHA', '.', '-f', './Dockerfile']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/decare:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'decare'
   - '--image'
   - 'gcr.io/$PROJECT_ID/decare:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   - '--add-cloudsql-instances'
   - 'dementia-cares:asia-southeast2:dementia-care'
   - '--set-env-vars'
   - 'CLOUD_SQL_CONNECTION_NAME=dementia-cares:asia-southeast2:dementia-care'
 images:
 - 'gcr.io/$PROJECT_ID/decare:$COMMIT_SHA'